In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("products.xlsx")

In [3]:
df

,Product_ID,Product_Name,Brand,Category,Amazon_URL,Flipkart_URL
0,P001,iPhone 17 Pro Max 1 TB,Apple,Smartphone,https://www.amazon.in/dp/B0FQFPHB1W,https://www.flipkart.com/apple-iphone-17-pro-m...
1,P002,Samsung Galaxy S25,Samsung,Smartphone,https://www.amazon.in/Samsung-Icyblue-Storage-...,https://www.flipkart.com/samsung-galaxy-s25-5g...
2,P003,OnePlus 13 (256GB),OnePlus,Smartphone,https://www.amazon.in/OnePlus-13-256GB-Midnigh...,https://www.flipkart.com/oneplus-13-midnight-o...
3,P004,Google Pixel 9a (256GB),Google,Smartphone,https://www.amazon.in/Google-Pixel-Obsidian-25...,https://www.flipkart.com/google-pixel-9a-iris-...
4,P005,HP Victus i7,HP,Laptop,https://www.amazon.in/HP-Smartchoice-i7-13620H...,https://www.flipkart.com/hp-victus-intel-core-...
5,P006,Lenovo LOQ 2024 i5,Lenovo,Laptop,https://www.amazon.in/Lenovo-i5-13450HX-300Nit...,https://www.flipkart.com/lenovo-loq-intel-core...
6,P007,boAt Airdopes 181,boAt,Earbuds,https://www.amazon.in/boAt-Airdopes-Playback-T...,https://www.flipkart.com/boat-airdopes-181-pro...
7,P008,Sony WH-CH520,Sony,Headphones,https://www.amazon.in/Sony-Bluetooth-Headphone...,https://www.flipkart.com/sony-wh-ch520-lz-blue...
8,P009,Logitech M331 Silent Plus,Logitech,Accessories,https://www.amazon.in/Logitech-Silent-Wireless...,https://www.flipkart.com/logitech-m331-silent-...
9,P010,Apple Watch SE GPS 40mm,Apple,Smartwatch,https://www.amazon.in/Apple-Watch-Midnight-Alu...,https://www.flipkart.com/apple-watch-se-3-2025...

In [4]:
df.head(5)

,Product_ID,Product_Name,Brand,Category,Amazon_URL,Flipkart_URL
0,P001,iPhone 17 Pro Max 1 TB,Apple,Smartphone,https://www.amazon.in/dp/B0FQFPHB1W,https://www.flipkart.com/apple-iphone-17-pro-m...
1,P002,Samsung Galaxy S25,Samsung,Smartphone,https://www.amazon.in/Samsung-Icyblue-Storage-...,https://www.flipkart.com/samsung-galaxy-s25-5g...
2,P003,OnePlus 13 (256GB),OnePlus,Smartphone,https://www.amazon.in/OnePlus-13-256GB-Midnigh...,https://www.flipkart.com/oneplus-13-midnight-o...
3,P004,Google Pixel 9a (256GB),Google,Smartphone,https://www.amazon.in/Google-Pixel-Obsidian-25...,https://www.flipkart.com/google-pixel-9a-iris-...
4,P005,HP Victus i7,HP,Laptop,https://www.amazon.in/HP-Smartchoice-i7-13620H...,https://www.flipkart.com/hp-victus-intel-core-...

In [5]:
df.tail()

,Product_ID,Product_Name,Brand,Category,Amazon_URL,Flipkart_URL
5,P006,Lenovo LOQ 2024 i5,Lenovo,Laptop,https://www.amazon.in/Lenovo-i5-13450HX-300Nit...,https://www.flipkart.com/lenovo-loq-intel-core...
6,P007,boAt Airdopes 181,boAt,Earbuds,https://www.amazon.in/boAt-Airdopes-Playback-T...,https://www.flipkart.com/boat-airdopes-181-pro...
7,P008,Sony WH-CH520,Sony,Headphones,https://www.amazon.in/Sony-Bluetooth-Headphone...,https://www.flipkart.com/sony-wh-ch520-lz-blue...
8,P009,Logitech M331 Silent Plus,Logitech,Accessories,https://www.amazon.in/Logitech-Silent-Wireless...,https://www.flipkart.com/logitech-m331-silent-...
9,P010,Apple Watch SE GPS 40mm,Apple,Smartwatch,https://www.amazon.in/Apple-Watch-Midnight-Alu...,https://www.flipkart.com/apple-watch-se-3-2025...

In [6]:
df.shape

(10, 6)

In [7]:
df.columns

Index(['Product_ID', 'Product_Name', 'Brand', 'Category', 'Amazon_URL',
       'Flipkart_URL'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    10 non-null     object
 1   Product_Name  10 non-null     object
 2   Brand         10 non-null     object
 3   Category      10 non-null     object
 4   Amazon_URL    10 non-null     object
 5   Flipkart_URL  10 non-null     object
dtypes: object(6)
memory usage: 612.0+ bytes

In [9]:
df["Product_Name"]

0       iPhone 17 Pro Max 1 TB
1           Samsung Galaxy S25
2           OnePlus 13 (256GB)
3      Google Pixel 9a (256GB)
4                 HP Victus i7
5           Lenovo LOQ 2024 i5
6            boAt Airdopes 181
7                Sony WH-CH520
8    Logitech M331 Silent Plus
9      Apple Watch SE GPS 40mm
Name: Product_Name, dtype: object

In [11]:
df["Amazon_URL"]

0                  https://www.amazon.in/dp/B0FQFPHB1W
1    https://www.amazon.in/Samsung-Icyblue-Storage-...
2    https://www.amazon.in/OnePlus-13-256GB-Midnigh...
3    https://www.amazon.in/Google-Pixel-Obsidian-25...
4    https://www.amazon.in/HP-Smartchoice-i7-13620H...
5    https://www.amazon.in/Lenovo-i5-13450HX-300Nit...
6    https://www.amazon.in/boAt-Airdopes-Playback-T...
7    https://www.amazon.in/Sony-Bluetooth-Headphone...
8    https://www.amazon.in/Logitech-Silent-Wireless...
9    https://www.amazon.in/Apple-Watch-Midnight-Alu...
Name: Amazon_URL, dtype: object

In [15]:
df.iloc[0]

Product_ID                                                   P001
Product_Name                               iPhone 17 Pro Max 1 TB
Brand                                                      Apple
Category                                               Smartphone
Amazon_URL                    https://www.amazon.in/dp/B0FQFPHB1W
Flipkart_URL    https://www.flipkart.com/apple-iphone-17-pro-m...
Name: 0, dtype: object

In [13]:
df.iloc[1]

Product_ID                                                   P002
Product_Name                                   Samsung Galaxy S25
Brand                                                     Samsung
Category                                               Smartphone
Amazon_URL      https://www.amazon.in/Samsung-Icyblue-Storage-...
Flipkart_URL    https://www.flipkart.com/samsung-galaxy-s25-5g...
Name: 1, dtype: object

In [14]:
df.iloc[0]["Product_Name"]

'iPhone 17 Pro Max 1 TB'

In [16]:
df.iloc[0]["Amazon_URL"]

'https://www.amazon.in/dp/B0FQFPHB1W'

In [17]:
df.iloc[0]["Flipkart_URL"]

'https://www.flipkart.com/apple-iphone-17-pro-max-cosmic-orange-1-tb/p/itm1f80bd9e45636'

In [18]:
for index, row in df.iterrows():
    print(row["Product_Name"])

iPhone 17 Pro Max 1 TB
Samsung Galaxy S25
OnePlus 13 (256GB)
Google Pixel 9a (256GB)
HP Victus i7
Lenovo LOQ 2024 i5
boAt Airdopes 181
Sony WH-CH520
Logitech M331 Silent Plus
Apple Watch SE GPS 40mm

In [19]:
for index, row in df.iterrows():
    print(row["Product_Name"])
    print(row["Amazon_URL"])
    print("-"*60)

iPhone 17 Pro Max 1 TB
https://www.amazon.in/dp/B0FQFPHB1W
------------------------------------------------------------
Samsung Galaxy S25
https://www.amazon.in/Samsung-Icyblue-Storage-Snapdragon-Display/dp/B0H2J3PRKV
------------------------------------------------------------
OnePlus 13 (256GB)
https://www.amazon.in/OnePlus-13-256GB-Midnight-Ocean/dp/B0DPS7FB4J
------------------------------------------------------------
Google Pixel 9a (256GB)
https://www.amazon.in/Google-Pixel-Obsidian-256-RAM/dp/B0F6CY1S9Z
------------------------------------------------------------
HP Victus i7
https://www.amazon.in/HP-Smartchoice-i7-13620H-Upgradeable-Office24/dp/B0FDKS93JV
------------------------------------------------------------
Lenovo LOQ 2024 i5
https://www.amazon.in/Lenovo-i5-13450HX-300Nits-Graphics-83DV007GIN/dp/B0D49W5KZP
------------------------------------------------------------
boAt Airdopes 181
https://www.amazon.in/boAt-Airdopes-Playback-Technology-Bluetooth/dp/B0F9X4NPYN
------------------------------------------------------------
Sony WH-CH520
https://www.amazon.in/Sony-Bluetooth-Headphones-Multipoint-Connectivity/dp/B0BS1RT9S2
------------------------------------------------------------
Logitech M331 Silent Plus
https://www.amazon.in/Logitech-Silent-Wireless-Mouse-Black/dp/B01MQ2A86A
------------------------------------------------------------
Apple Watch SE GPS 40mm
https://www.amazon.in/Apple-Watch-Midnight-Aluminium-Sport/dp/B0FQFNRHQC
------------------------------------------------------------

In [23]:
import playwright